### ISSUE TITLE
Cannot install for 32 bit machines

### ISSUE THREAD

**Issue by BoundaryValueProblems** [JuliaPackaging/CMakeWrapper.jl#10] opened 2018-05-21 16:18 UTC
Has CMakeWrapper.jl been installed and tested on 32 bit machines? I couldn't install it on my 32 bit machine running Ubuntu/Linux 16.04.4 LTS. On the other hand, I didn't have any problems installing it on 64 bit machines. It generated a whole bunch of compilation errors such as:
```
g++  -I/home/xxx/.julia/v0.6/CMakeWrapper/deps/src/cmake-3.7.2/Bootstrap.cmk -I/home/xxx/.julia/v0.6/CMakeWrapper/deps/src/cmake-3.7.2/Source   -I/home/xxx/.julia/v0.6/CMakeWrapper/deps/src/cmake-3.7.2/Utilities -c /home/xxx/.julia/v0.6/CMakeWrapper/deps/src/cmake-3.7.2/Source/cmake.cxx -o cmake.o
In file included from /home/xxx/.julia/v0.6/CMakeWrapper/deps/src/cmake-3.7.2/Source/cmake.h:6:0,
                 from /home/xxx/.julia/v0.6/CMakeWrapper/deps/src/cmake-3.7.2/Source/cmake.cxx:3:
/home/xxx/.julia/v0.6/CMakeWrapper/deps/src/cmake-3.7.2/Source/cmLinkedTree.h In constructor ‘cmLinkedTree<T>::iterator::iterator()’:
/home/xxx/.julia/v0.6/CMakeWrapper/deps/src/cmake-3.7.2/Source/cmConfigure.h:35:20: error: ‘nullptr’ was not declared in this scope
 #define CM_NULLPTR nullptr
                    ^
```
And in the end, it says:
```
Makefile:4: recipe for target 'cmake.o' failed
make: *** [cmake.o] Error 1
---------------------------------------------
Error when bootstrapping CMake:
Problem while running make
---------------------------------------------
Log of errors: /home/xxx/.julia/v0.6/CMakeWrapper/deps/src/cmake-3.7.2/Bootstrap.cmk/cmake_bootstrap.log
---------------------------------------------
============================[ ERROR: CMakeWrapper ]=============================

LoadError: failed process: Process(`./configure --prefix=/home/xxx/.julia/v0.6/CMakeWrapper/deps/usr`, ProcessExited(9)) [9]
while loading /home/xxx/.julia/v0.6/CMakeWrapper/deps/build.jl, in expression starting on line 125
```
I also should mention that my 32 bit linux machine has its ```cmake``` installed in /usr/bin. Thanks for your help!

**Comment by rdeits** [comment] 2018-05-21 22:05
We build and test this on 32-bit Windows systems but only 64-bit Linux (I'm basically limited by what's available on Travis CI and Appveyor). 

However, it looks like in this case the problem is that we're trying to compile CMake without C++-11 support (since `nullptr` was defined in C++-11. I'm not sure why that's happening. 

If you can help out, I bet we can fix this. The `CMakeWrapper.jl` build process just tries to download https://cmake.org/files/v3.7/cmake-3.7.2.tar.gz and compile it with the standard autotools process (`./configure; make; make install`). Can you try doing that manually and report the result?

**Comment by BoundaryValueProblems** [comment] 2018-05-22 03:28
@rdeits , I just downloaded cmake-3.7.2.tar.gz, compiled it and installed it on my 32 bit ubuntu/linux machine without any error. I even didn't get any warning messages. The log file is quite lengthy, but would you like to see it? Let me know. Basically ./configure checked if int64 type is available or not (no on 32 bit machines), and various options, and dealt these situations nicely.
Thanks!

**Comment by rdeits** [comment] 2018-05-22 03:50
Ok, thank you for checking. That's very strange--the steps that Julia's BinDeps is doing should be essentially the same as what you did manually. 

Could you check two things for me? 

1) You mentioned seeing the `./configure` doing the appropriate int64 checks. When you do `Pkg.build("CMakeWrapper")`, do you also see those checks done correctly? (you may need to delete your `~/.julia/v0.6/CMakeWrapper/deps/src` folder to ensure that configuration is done again)

2) Can you edit BinDeps.jl to print out the `cmd` here: https://github.com/JuliaLang/BinDeps.jl/blob/69c3fb64f35b5e92c866323ba217e6d4f8f82ae7/src/BinDeps.jl#L414 so we can see what `make` command is being run?

**Comment by BoundaryValueProblems** [comment] 2018-05-22 17:05
@rdeits , I tried your suggested item 1 first. After deleting ```~/.julia/v0.6/CMakeWrapper/deps/src``` folder, the installation process made much more progress. For example, the following kind of compilations associated with ```./configure``` completed, 
```
g++  -I/home/xxx/.julia/v0.6/CMakeWrapper/deps/src/cmake-3.7.2/Bootstrap.cmk -I/home/xxx/.julia/v0.6/CMakeWrapper/deps/src/cmake-3.7.2/Source   -I/home/xxx/.julia/v0.6/CMakeWrapper/deps/src/cmake-3.7.2/Utilities -c /home/xxx/.julia/v0.6/CMakeWrapper/deps/src/cmake-3.7.2/Source/cmake.cxx -o cmake.o
```
And ```int64``` was checked since it says:
```
-- Checking whether C++ compiler has '__int64' - no
```
Then it started running ```make```. Unfortunately, it didn't complete. It made a lot of progress: it reached 70% of the whole thing. The following is the output of that portion:
```
[ 70%] Building CXX object Source/CMakeFiles/CMakeLib.dir/cmCPackPropertiesGenerator.cxx.o
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Source/CMakeFiles/CMakeLib.dir/build.make:350: recipe for target 'Source/CMakeFiles/CMakeLib.dir/cmComputeLinkDepends.cxx.o' failed
make[2]: *** [Source/CMakeFiles/CMakeLib.dir/cmComputeLinkDepends.cxx.o] Error 4
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:2008: recipe for target 'Source/CMakeFiles/CMakeLib.dir/all' failed
make[1]: *** [Source/CMakeFiles/CMakeLib.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```
I tried the same process all over again, and it reached to 74% completion, but again with the similar error: ```g++: internal compiler error: Killed (program cc1plus)```.

**Comment by rdeits** [comment] 2018-05-22 20:22
Ok, that's interesting. It looks like you might just be running out of memory. Perhaps what's happening is that the additional memory usage of Julia itself is causing your system to run out of RAM while compiling, even though you have (barely) enough to compile outside of Julia.

Can you try watching your system's memory consumption during the compilation? 

You can also try removing the `-j8` flag here: https://github.com/JuliaLang/BinDeps.jl/blob/69c3fb64f35b5e92c866323ba217e6d4f8f82ae7/src/BinDeps.jl#L396 and repeating the build. Removing that flag will stop the build from running in parallel, which should make it slower but less memory-hungry.

**Comment by BoundaryValueProblems** [comment] 2018-05-22 21:46
@rdeits Good news! I logged out from my 32 bit machine, and remotely logged in via terminal (i.e., no graphical interfaces, etc.) so that I didn't use the memory much. Then I repeated the installation process via ```Pkg.build("CMakeWrapper")```, and now it has been correctly installed! Thanks!

**Comment by rdeits** [comment] 2018-05-22 21:50
Excellent! Sounds like it's definitely a RAM issue. I'd suggest adding more swap space if possible of this happens again. 

Ok to close this issue?

**Comment by BoundaryValueProblems** [comment] 2018-05-22 22:51
Yes, please close this issue. BTW, in my trial above, I didn't have to remove the ```-j8``` flag from ```make``` in ```BinDeps.jl```. Overall, I feel that my 32 bit machine should retire soon (yet it's still working though slow).

**Closed as completed** 2018-05-22 23:08 UTC
